/*
 * The MIT License
 *
 * Copyright 2022 DimasFerreira.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.projeto_kevin.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.projeto_kevin.ctr.ClienteCTR;
import br.com.projeto_kevin.dto.ClienteDTO;
import br.com.projeto_kevin.ctr.ProdutoCTR;
import br.com.projeto_kevin.dao.ConexaoDAO;
import br.com.projeto_kevin.dto.ProdutoDTO;
import br.com.projeto_kevin.dto.VendaDTO;
import java.text.SimpleDateFormat;

import java.sql.*;
import java.awt.Dimension;

/**
 *
 * @author DimasFerreira
 */
public class CompraVIEW extends javax.swing.JInternalFrame {

    private ResultSet rs = null;
    Statement stmt = null;
    Statement stmt1 = null;
    DefaultTableModel modelo_jtl_cliente;
    DefaultTableModel modelo_jtl_produto;
    ClienteDTO clienteDTO = new ClienteDTO();
    ClienteCTR clienteCTR = new ClienteCTR();
    ProdutoDTO produtoDTO = new ProdutoDTO();
        SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
    ProdutoCTR produtoCTR = new ProdutoCTR();
        VendaDTO vendaDTO = new VendaDTO();


    public CompraVIEW() {
        initComponents();
        modelo_jtl_cliente = (DefaultTableModel) jtl_cliente.getModel();
        modelo_jtl_produto = (DefaultTableModel) jtl_produto.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void salvarCliente(int id_cliente) {

        try {
            clienteDTO.setId_cliente(id_cliente);
            ResultSet rs = clienteCTR.consultarCliente(clienteDTO, 1);
            if (rs.next()) {
                rs.getString("id_cliente");
                rs.getString("nome");
                rs.getString("telefone");
                rs.getString("cpf");
            } else {
                JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
            }
        } catch (Exception ex) {
            System.out.println("Erro: " + ex.getMessage());
        } finally {
            clienteCTR.CloseDB();
        }
    }

    public boolean inserirVenda() {
        try {
            stmt = ConexaoDAO.con.createStatement();
            stmt1 = ConexaoDAO.con.createStatement();

            String comando1 = "Insert into Comprou (id_cliente) values ( "
                      +"to_date('" + date.format(vendaDTO.getDat_vend()) + "', 'DD/MM/YYYY'), "
                    + clienteDTO.getId_cliente() + ")";

            stmt.execute(comando1.toUpperCase(), Statement.RETURN_GENERATED_KEYS);
            rs = stmt.getGeneratedKeys();
            rs.next();

            for (int cont = 0; cont < modelo_jtl_produto.getRowCount(); cont++) {
                String comando2 = "Insert into Venda (id_vend, id_prod, "
                        + ") values ("
                        + rs.getInt("id_vend") + ", "
                        + modelo_jtl_produto.getValueAt(cont, 0) + ", "
     
                        + modelo_jtl_produto.getValueAt(cont, 2) + "); ";

                stmt1.execute(comando2);
            }

            ConexaoDAO.con.commit();
            stmt.close();
            rs.close();
            return true;
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return false;
        } finally {
            ConexaoDAO.CloseDB();
        }
    }

    private void preencheTabela(String nome) {
        try {
            //Limpa todas as linhas
            modelo_jtl_cliente.setNumRows(0);
            //Enquanto tiver linhas - faça
            clienteDTO.setNome(nome);
            rs = clienteCTR.consultarCliente(clienteDTO, 1);
            while (rs.next()) {
                modelo_jtl_cliente.addRow(new Object[]{
                    rs.getString("id_cliente"),
                    rs.getString("nome"),
                    rs.getString("telefone"),
                    rs.getString("cpf"),});

            }
        } catch (Exception erTab) {
            System.out.println("Errp SQL" + erTab);
        } finally {
            clienteCTR.CloseDB();
        }
    }

    private void preencheTabelaProduto(String produto) {
        try {
            //Limpa todas as linhas
            modelo_jtl_produto.setNumRows(0);
            //Enquanto tiver linhas - faça
            produtoDTO.setProduto(produtoDTO.getProduto());
            rs = produtoCTR.consultarProduto(produtoDTO, 1);
            while (rs.next()) {
                modelo_jtl_produto.addRow(new Object[]{
                    rs.getString("produto"),
                    rs.getString("valor"),});

            }
        } catch (Exception erTab) {
            System.out.println("Errp SQL" + erTab);
        } finally {
            clienteCTR.CloseDB();
        }
    }

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtl_cliente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtl_produto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        pesquisa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        produto = new javax.swing.JTextField();
        pesquisar_produto = new javax.swing.JButton();
        salvar = new javax.swing.JButton();

        jtl_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_cliente", "Nome", "Telefone", "cpf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtl_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtl_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtl_cliente);
        if (jtl_cliente.getColumnModel().getColumnCount() > 0) {
            jtl_cliente.getColumnModel().getColumn(0).setResizable(false);
            jtl_cliente.getColumnModel().getColumn(1).setResizable(false);
            jtl_cliente.getColumnModel().getColumn(2).setResizable(false);
            jtl_cliente.getColumnModel().getColumn(3).setResizable(false);
        }

        jtl_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtl_produto);
        if (jtl_produto.getColumnModel().getColumnCount() > 0) {
            jtl_produto.getColumnModel().getColumn(0).setResizable(false);
            jtl_produto.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("Pesquisar nome:");

        pesquisa.setText("jButton1");
        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisa produto:");

        pesquisar_produto.setText("jButton1");
        pesquisar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar_produtoActionPerformed(evt);
            }
        });

        salvar.setText("jButton1");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisa)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(produto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisar_produto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(salvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisa)
                    .addComponent(jLabel2)
                    .addComponent(produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisar_produto))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(salvar)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtl_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtl_clienteMouseClicked


    }//GEN-LAST:event_jtl_clienteMouseClicked

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        preencheTabela(nome.getText());
    }//GEN-LAST:event_pesquisaActionPerformed

    private void pesquisar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar_produtoActionPerformed
        preencheTabelaProduto(produto.getText());
    }//GEN-LAST:event_pesquisar_produtoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        inserirVenda();
    }//GEN-LAST:event_salvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtl_cliente;
    private javax.swing.JTable jtl_produto;
    private javax.swing.JTextField nome;
    private javax.swing.JButton pesquisa;
    private javax.swing.JButton pesquisar_produto;
    private javax.swing.JTextField produto;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables

}
